const crypto=require('crypto');const net=require('net');
function fail(c,m,code='INVALID_CRAWL'){if(c){const e=new Error(m);e.code=code;throw e;}}
function isPublicAddress(address){
  if(net.isIP(address)===4){const p=address.split('.').map(Number);return !(p[0]===10||p[0]===127||p[0]===0||p[0]>=224||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127));}
  if(net.isIP(address)===6){const a=address.toLowerCase();return !(a==='::1'||a==='::'||a.startsWith('fc')||a.startsWith('fd')||a.startsWith('fe8')||a.startsWith('fe9')||a.startsWith('fea')||a.startsWith('feb')||a.startsWith('::ffff:'))};return false;
}
function normalizeUrl(raw,allowedHosts){let url;try{url=new URL(raw);}catch{fail(true,'valid URL required');}fail(url.protocol!=='https:','HTTPS is required');fail(url.username||url.password,'URL credentials are forbidden');fail(net.isIP(url.hostname)||url.hostname==='localhost'||url.hostname.endsWith('.local'),'IP literal and local hosts are forbidden','SSRF_BLOCKED');const hosts=(allowedHosts||[]).map(h=>h.toLowerCase());fail(!hosts.includes(url.hostname.toLowerCase()),'host is outside exact allowlist','OUT_OF_SCOPE');url.hash='';return url.toString();}
function validateJob(input){
  fail(!input||typeof input!=='object','crawl job required');const hosts=[...new Set(input.allowedHosts||[])].map(h=>String(h).toLowerCase()).sort();fail(hosts.length<1||hosts.length>20,'1-20 allowlisted hosts required');fail(hosts.some(h=>net.isIP(h)||h==='localhost'||h.endsWith('.local')||!/^[a-z0-9.-]+$/.test(h)),'allowlist contains invalid host');
  const startUrls=(input.startUrls||[]).map(u=>normalizeUrl(u,hosts));fail(startUrls.length<1||startUrls.length>100,'1-100 start URLs required');const rate=Number(input.requestsPerMinute);fail(!Number.isInteger(rate)||rate<1||rate>30,'rate must be 1-30 requests/minute');fail(input.robotsPolicy!=='enforce','robots enforcement is required');fail(!/^[a-f0-9]{64}$/.test(input.robotsEvidenceDigest||''),'robots evidence SHA-256 required');
  const schema=input.extractionSchema;fail(!schema||schema.type!=='object'||!schema.properties||Object.keys(schema.properties).length>100,'bounded object extraction schema required');
  const plan={allowedHosts:hosts,startUrls,requestsPerMinute:rate,robotsPolicy:'enforce',robotsEvidenceDigest:input.robotsEvidenceDigest,userAgent:String(input.userAgent||'GovernedCrawler/1.0').slice(0,120),extractionSchema:schema,maxPages:Math.min(Math.max(Number(input.maxPages)||1,1),10000),maxBytesPerPage:Math.min(Math.max(Number(input.maxBytesPerPage)||1024,1024),10_000_000),contractVersion:String(input.contractVersion||'v1')};
  return{plan,digest:crypto.createHash('sha256').update(JSON.stringify(plan)).digest('hex')};
}
function validateResolvedAddresses(addresses){fail(!Array.isArray(addresses)||!addresses.length,'DNS resolution evidence required','DNS_REQUIRED');fail(addresses.some(a=>!isPublicAddress(a)),'DNS resolved to a non-public address','SSRF_BLOCKED');return true;}
function canonicalRecord(input,plan){const canonicalUrl=normalizeUrl(input.canonicalUrl,plan.allowedHosts);fail(!input.data||typeof input.data!=='object'||Array.isArray(input.data),'object extraction required');const allowed=new Set(Object.keys(plan.extractionSchema.properties));fail(Object.keys(input.data).some(k=>!allowed.has(k)),'record contains fields outside contract');const record={canonicalUrl,data:input.data,sourceObservedAt:input.sourceObservedAt,contentDigest:input.contentDigest};fail(!/^[a-f0-9]{64}$/.test(record.contentDigest||''),'content digest required');return record;}
module.exports={isPublicAddress,normalizeUrl,validateJob,validateResolvedAddresses,canonicalRecord};
